

<!-- Footer -->
<footer class="container-fluid footer font-small py-3 hide-on-print">

    <!-- Copyright -->
    <div class="footer-copyright text-center">

    <!-- Adresse -->
    <span><b>Adresse: </b>Johannes Fog A/S - Firskovvej 20 - 2800 Lyngby - CVR-nr. 16314439 &bull;

    <!-- Telefon -->
    <b>Telefon: </b><a href="tel:45-87-10-01">45 87 10 01 </a> &bull;

    <!-- Email -->
    <b>Email:</b> <a href="mailto:info@johannesfog.dk">info@johannesfog.dk</a> &bull;
    </span>
    <span>
    &copy; 2020 All rights reserved:
      <a href="#"> Johannesfog.dk</a>
      </span>
    </div>
    <!-- Copyright -->

 </footer>
<!-- Footer -->

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<script src="js/validate.js" type="text/javascript"></script>
</body>
</html>