<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Responsive -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- External CSS -->
    <link rel="styleshess" type="text/css">
    <!-- Google font -->
    <link rel="stylesheet" href="#">
    <!-- header title -->
    <title>${requestScope.message}</title>
</head>
<body>
<header role="banner">
    <a class="navbar-brand" href="index.jsp" title="Logo">
        <img src="_images/logo.PNG" alt="Fog logo">
    </a>

</header>et" href="_css/styles.c
<nav role="navigation" class="navbar navbar-dark">
<div class="leftNav navbar-nav navbar-expand-sm sticky-top">
        <a class="nav-item nav-link align-content-center active" href="index.jsp" title="">Home</a>
        <a class="nav-item nav-link" href="FrontController?target=redirect&destination=customerpage" title="">Bestil</a>
    </div>
    <div class="navbar-nav navbar-expand-sm ml-sm-auto">
        <a class="nav-item nav-link" href="FrontController?target=redirect&destination=login" title="">Log ind</a>
    </div>
</nav>