@startuml

package "DBAccess" #fa9696 {

Class UserMapper{
{static}+void createUser(User)
{static}+User login(email, password)
}

class Connector{
{static}-String URL
{static}-String USERNAME
{static}-String PASSWORD
{static}-Connection singleton
{static}+Connection connection()
{static}+void setConnection(con)
}

}
/'
Comment
'/

package "FunctionLayer" #96c4fa {

LogicFacade <--> UserMapper
Connector <--> UserMapper
UserMapper <--> User

class CarportCalculation{
-double carportLength
-double carportWidth
-int customerRoofAngle
-int calcAngel
-double calcRaftLength
-double calcRoofHeight
-void populateAngleAndFactor()
-void calcRoofAngle()
-void calcRaftLength()
-void calcRoofHeight()
}

class LogicFacade {
{static}+User login(email, password)
{static}+User createUser(email, password)
}

class LoginSampleException extends Exception{
+LoginSampleException(msg)
}

class User{
-String email
-String id
-String password
-String role
+User(email, password, role)
}

}

package "PresentationLayer" #78d683 {

FrontController --|> Command

class Command{
{Static}-HashMap: String, command
{Static}-void initCommands()
{Static}+Command from(request)
{abstract} String execute()
}

class CarportCalcPage extends Command{
{Static}+String execute(request, response)
}

class FrontController extends HttpServlet{
{Static}#void processRequest(request, response)
{Static}#void doGet(request, response)
{Static}#void doPost(request, response)
{Static}#void getServletInfo()
}

class Login extends Command{
{Static}+String execute(request,response)
}

class Redirect extends Command{
{Static}+String execute(request,response)
}

class Register extends Command{
{Static}+String execute(request,response)
}

class UnknownCommand extends Command{
{Static}+String execute(request,response)
}

}

@enduml