@startuml
(*) --> "index.jsp"
"index.jsp" --> "login.jsp"
"index.jsp" --> "customerpage.jsp"

"adminpage.jsp" --> [Login Error] "login.jsp"
"login.jsp" --> "adminpage.jsp"
"adminpage.jsp" --> [Logout] "index.jsp"
"adminpage.jsp" -> "adminQuoteView.jsp"
"adminQuoteView.jsp" -left-> [Logout] "index.jsp"
"adminQuoteView.jsp" -> "adminDrawing.jsp"
"adminDrawing.jsp" -left-> [Logout] "index.jsp"
"adminQuoteView.jsp" --> "customerReceipt.jsp"

partition "Admin Drop Down Menu" #FFF8DC{
"adminpage.jsp" --> === S2 ===
=== S2 === -right-> [Updated measurements and items] "adminpage.jsp"

=== S2 === --> "ItemList.jsp"
=== S2 === -left> "adminMeasurementUnits.jsp"
=== S2 === -> "adminRafterSpacing.jsp"
=== S2 === --> "adminRoof.jsp"
=== S2 === --> "adminRoofPitch.jsp"
=== S2 === --> "adminStandardDimensions.jsp"
}

"customerpage.jsp" --> [Choose carport type] "customerCarportCustomize.jsp"
"customerpage.jsp" --> "customerCarportStandard.jsp"
"customerCarportCustomize.jsp" --> [Generate quotation receipt] "customerReceipt.jsp"
"customerCarportStandard.jsp" --> "customerReceipt.jsp"


@enduml